version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes: 
      - ./data:/data/database
    ports: 
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/clean-node
    restart: always
    command: bash -c "yarn install --only=prod && yarn debug"
    environment: 
      - MONGO_URL=mongodb://mongo:27017/clean-server
    volumes:
      - ./build:/usr/src/clean-node/build/
      - ./package.json:/usr/src/clean-node/package.json
    ports: 
      - "3333:3333"
      - "9222:9222"
    links: 
      - mongo